namespace InsightDesk.Reports;

/// <summary>
/// Represents product quantity performance.
/// </summary>
public record ProductSalesReport(
    string ProductName,
    int TotalQuantity);

/// <summary>
/// Represents revenue generated by a category.
/// </summary>
public record CategoryRevenueReport(
    string Category,
    decimal Revenue);

/// <summary>
/// Represents staff sales performance.
/// </summary>
public record StaffPerformanceReport(
    string StaffName,
    int SalesCount,
    decimal TotalRevenue,
    decimal AverageSaleValue);

/// <summary>
/// Represents sales activity for one hour.
/// </summary>
public record HourlySalesReport(
    int Hour,
    int SalesCount,
    decimal Revenue);

/// <summary>
/// Represents revenue performance of a store category.
/// </summary>
public record StoreCategoryRevenue(
    string Category,
    decimal Revenue);

/// <summary>
/// Represents store-level sales performance.
/// </summary>
public record StoreComparisonReport(
    string StoreLocation,
    decimal Revenue,
    int ItemCount,
    string TopCategory,
    decimal TopCategoryRevenue);