using InsightDesk.Models;
using InsightDesk.Reports;

namespace InsightDesk.Services;

/// <summary>
/// Provides LINQ-based analytics over retail sales and promotions.
/// </summary>
public class SalesAnalyticsEngine
{
    private readonly List<SaleLineItem> _sales;
    private readonly List<Promotion> _promotions;

    /// <summary>
    /// Creates an analytics engine using the supplied sales and promotions.
    /// </summary>
    public SalesAnalyticsEngine(
        List<SaleLineItem> sales,
        List<Promotion> promotions)
    {
        _sales = sales ?? new List<SaleLineItem>();
        _promotions = promotions ?? new List<Promotion>();
    }

     
    // 1. TOP SELLING PRODUCTS
    // Method syntax
    /// <summary>
    /// Returns the top N products based on total quantity sold.
    /// </summary>
    public IEnumerable<ProductSalesReport> TopSellingProducts(int topN)
    {
        if (topN <= 0)
        {
            return Enumerable.Empty<ProductSalesReport>();
        }

        return _sales
            .GroupBy(sale => sale.ProductName)
            .Select(group => new ProductSalesReport(
                group.Key,
                group.Sum(sale => sale.Quantity)))
            .OrderByDescending(report => report.TotalQuantity)
            .Take(topN);
    }

     
    // 2. REVENUE BY CATEGORY
    // Query syntax
    /// <summary>
    /// Returns total revenue generated by each product category,
    /// ordered from highest revenue to lowest revenue.
    /// </summary>
    public IEnumerable<CategoryRevenueReport> RevenueByCategory()
    {
        var query =
            from sale in _sales
            group sale by sale.Category
            into categoryGroup
            let revenue = categoryGroup.Sum(sale => sale.LineTotal)
            orderby revenue descending
            select new CategoryRevenueReport(
                categoryGroup.Key,
                revenue);

        // No ToList() is intentionally used here.
        // The returned query demonstrates deferred execution.
        return query;
    }

     
    // 3. STAFF PERFORMANCE
    // Method syntax
    /// <summary>
    /// Returns sales count, revenue and average sale value
    /// for every staff member.
    /// </summary>
    public IEnumerable<StaffPerformanceReport> StaffPerformanceReport()
    {
        return _sales
            .GroupBy(sale => sale.StaffName)
            .Select(group => new StaffPerformanceReport(
                group.Key,
                group.Count(),
                group.Sum(sale => sale.LineTotal),
                group.Average(sale => sale.LineTotal)))
            .OrderByDescending(report => report.TotalRevenue)
            .ThenBy(report => report.StaffName);
    }

     
    // 4. HOURLY SALES TREND
    // Query syntax
    /// <summary>
    /// Groups sales by the hour in which they occurred and
    /// returns sales count and revenue for each hour.
    /// </summary>
    public IEnumerable<HourlySalesReport> HourlySalesTrend()
    {
        var query =
            from sale in _sales
            group sale by sale.SoldAt.Hour
            into hourGroup
            orderby hourGroup.Key
            select new HourlySalesReport(
                hourGroup.Key,
                hourGroup.Count(),
                hourGroup.Sum(sale => sale.LineTotal));

        // Deliberately return the query without ToList()
        // to demonstrate deferred execution.
        return query;
    }

     
    // 5. PERCENT-OFF PROMOTIONS
    // Method syntax
    /// <summary>
    /// Returns percentage-based promotions whose discount
    /// is greater than the supplied minimum percentage.
    /// </summary>
    public IEnumerable<PercentOffPromotion> PercentOffPromotionsOver(
        double minPercent)
    {
        return _promotions
            .OfType<PercentOffPromotion>()
            .Where(promotion => promotion.PercentOff > minPercent)
            .OrderBy(promotion => promotion.PercentOff);
    }

     
    // 6. LOW-PERFORMING CATEGORIES
    // Query syntax with continuation
    /// <summary>
    /// Returns categories whose total revenue is below
    /// the supplied revenue threshold.
    /// </summary>
    public IEnumerable<CategoryRevenueReport> LowPerformingCategories(
        decimal revenueThreshold)
    {
        var query =
            from sale in _sales
            group sale by sale.Category
            into categoryGroup
            let revenue = categoryGroup.Sum(sale => sale.LineTotal)
            where revenue < revenueThreshold
            orderby revenue
            select new CategoryRevenueReport(
                categoryGroup.Key,
                revenue);

        return query;
    }

     
    // 7. STORE COMPARISON
    // Method syntax
    /// <summary>
    /// Returns revenue, item count and the highest-revenue
    /// category for each store.
    /// </summary>
    public IEnumerable<StoreComparisonReport> StoreComparisonReport()
    {
        return _sales
            .GroupBy(sale => sale.StoreLocation)
            .Select(storeGroup =>
            {
                var categoryReport = storeGroup
                    .GroupBy(sale => sale.Category)
                    .Select(categoryGroup => new StoreCategoryRevenue(
                        categoryGroup.Key,
                        categoryGroup.Sum(sale => sale.LineTotal)))
                    .OrderByDescending(category => category.Revenue)
                    .ThenBy(category => category.Category)
                    .FirstOrDefault();

                return new StoreComparisonReport(
                    storeGroup.Key,
                    storeGroup.Sum(sale => sale.LineTotal),
                    storeGroup.Sum(sale => sale.Quantity),
                    categoryReport?.Category ?? "No Sales",
                    categoryReport?.Revenue ?? 0m);
            })
            .OrderByDescending(report => report.Revenue)
            .ThenBy(report => report.StoreLocation);
    }

     
    // 8. DEFERRED VS SNAPSHOT
    // Query syntax
    /// <summary>
    /// Demonstrates the difference between a deferred LINQ query
    /// and an immediately materialized snapshot.
    /// </summary>
    public void DeferredVsSnapshotDemo()
    {
        Console.WriteLine();
        Console.WriteLine("DEFERRED EXECUTION VS SNAPSHOT");
        Console.WriteLine(new string('-', 55));

        var deferredQuery =
            from sale in _sales
            where sale.Category == "Electronics"
            select sale;

        var snapshot =
            deferredQuery.ToList();

        Console.WriteLine(
            $"Before mutation -> Deferred: {deferredQuery.Count()}, Snapshot: {snapshot.Count}");

        var temporarySale = new SaleLineItem
        {
            Id = 999,
            ProductName = "Temporary Laptop",
            Category = "Electronics",
            UnitPrice = 50000,
            Quantity = 1,
            StaffName = "Demo",
            StoreLocation = "Delhi",
            SoldAt = new DateTime(2026, 8, 22, 22, 30, 0)
        };

        _sales.Add(temporarySale);

        Console.WriteLine(
            $"After mutation  -> Deferred: {deferredQuery.Count()}, Snapshot: {snapshot.Count}");

        Console.WriteLine();
        Console.WriteLine(
            "The deferred query reads the current list when enumerated,");
        Console.WriteLine(
            "while the ToList() snapshot keeps the earlier result.");

        _sales.Remove(temporarySale);
    }

     
    // 9. QUERY SYNTAX VS METHOD SYNTAX EQUIVALENCE
    /// <summary>
    /// Compares the method-syntax and query-syntax versions
    /// of the top-selling-products report.
    /// </summary>
    public void SyntaxEquivalenceCheck()
    {
        var methodSyntax = _sales
            .GroupBy(sale => sale.ProductName)
            .Select(group => new ProductSalesReport(
                group.Key,
                group.Sum(sale => sale.Quantity)))
            .OrderByDescending(report => report.TotalQuantity)
            .ThenBy(report => report.ProductName)
            .ToList();

        var querySyntax =
            (from sale in _sales
             group sale by sale.ProductName
             into productGroup
             let quantity = productGroup.Sum(sale => sale.Quantity)
             orderby quantity descending, productGroup.Key
             select new ProductSalesReport(
                 productGroup.Key,
                 quantity))
            .ToList();

        bool identical = methodSyntax.SequenceEqual(querySyntax);

        Console.WriteLine();
        Console.WriteLine("QUERY SYNTAX VS METHOD SYNTAX");
        Console.WriteLine(new string('-', 55));
        Console.WriteLine(
            $"Both implementations produce identical results: {identical}");
    }
     
    // 10. BROKEN STAFF SORT
    /// <summary>
    /// Demonstrates why calling OrderBy twice is incorrect when
    /// a secondary sort is required.
    /// </summary>
    public void BrokenStaffSort()
    {
        var broken = _sales
            .GroupBy(sale => sale.StaffName)
            .Select(group => new StaffPerformanceReport(
                group.Key,
                group.Count(),
                group.Sum(sale => sale.LineTotal),
                group.Average(sale => sale.LineTotal)))
            .OrderByDescending(report => report.TotalRevenue)
            .OrderBy(report => report.StaffName)
            .ToList();

        var corrected = StaffPerformanceReport().ToList();

        Console.WriteLine();
        Console.WriteLine("BROKEN VS CORRECT STAFF SORT");
        Console.WriteLine(new string('-', 75));

        Console.WriteLine(
            $"{ "Broken OrderBy", -30} | { "Correct OrderBy + ThenBy", -30}");
        Console.WriteLine(new string('-', 75));

        int max = Math.Max(broken.Count, corrected.Count);

        for (int i = 0; i < max; i++)
        {
            string brokenText = i < broken.Count
                ? $"{broken[i].StaffName} - {broken[i].TotalRevenue:C}"
                : "-";

            string correctedText = i < corrected.Count
                ? $"{corrected[i].StaffName} - {corrected[i].TotalRevenue:C}"
                : "-";

            Console.WriteLine(
                $"{brokenText,-30} | {correctedText,-30}");
        }

        Console.WriteLine();
        Console.WriteLine(
            "Explanation: a second OrderBy replaces the first ordering; " +
            "ThenBy preserves the primary ordering and applies a tie-breaker.");
    }
}